name: SnowCLI SQL Execution

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Configure SnowCLI
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: | 
        mkdir ~/.snowsql
        echo "[connections.awesome] \                               
        accountname = $(echo "$SNOWFLAKE_ACCOUNT") \
        username = $(echo "$SNOWFLAKE_USER") \
        password = $(echo "$SNOWFLAKE_PASSWORD")" > ~/.snowsql/config
        snow login --config ~/.snowsql/config --connection awesome
    - name: Execute SQL
      run: snow sql --query "SELECT 1;"
